version: "3"

services:
  mvp:
    # build: .
    container_name: mvp_repositorio_institucional
    image: node:16-alpine
    working_dir: /usr/src/mvp_repositorio/ 
    # npm run dockerDev
    command: sh -c "npm install --omit=dev && node dists/server.js"
    volumes:
      - ./dists/:/usr/src/mvp_repositorio/dists/
      - ./package.json:/usr/src/mvp_repositorio/package.json
      - ./public/:/usr/src/mvp_repositorio/public/
      # - ./yarn.lock:/usr/src/toDoList/yarn.lock
      # - ./yarn-error.log:/usr/src/toDoList/yarn-error.log
    # expose:
    #   - 2222
    ports:
      - "3000:3333"